/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.5 at Sat Apr 18 09:18:37 2015. */

#include "openiot.pb.h"


const pb_field_t OpenIoT_fields[1] = {
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_Header_fields[3] = {
        PB_FIELD2(1, ENUM, REQUIRED, STATIC, FIRST, OpenIoT_Header, command, command, 0),
        PB_FIELD2(2, STRING, OPTIONAL, STATIC, OTHER, OpenIoT_Header, originator, command, 0),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_Metadata_fields[3] = {
        PB_FIELD2(1, STRING, REQUIRED, CALLBACK, FIRST, OpenIoT_Metadata, name, name, 0),
        PB_FIELD2(2, STRING, REQUIRED, CALLBACK, OTHER, OpenIoT_Metadata, value, name, 0),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_RegisterDevice_fields[5] = {
        PB_FIELD2(1, STRING, REQUIRED, STATIC, FIRST, OpenIoT_RegisterDevice, hardwareId, hardwareId, 0),
        PB_FIELD2(2, STRING, REQUIRED, STATIC, OTHER, OpenIoT_RegisterDevice, specificationToken, hardwareId, 0),
        PB_FIELD2(3, MESSAGE, REPEATED, CALLBACK, OTHER, OpenIoT_RegisterDevice, metadata, specificationToken,
                  &OpenIoT_Metadata_fields),
        PB_FIELD2(4, STRING, OPTIONAL, CALLBACK, OTHER, OpenIoT_RegisterDevice, siteToken, metadata, 0),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_Acknowledge_fields[3] = {
        PB_FIELD2(1, STRING, REQUIRED, STATIC, FIRST, OpenIoT_Acknowledge, hardwareId, hardwareId, 0),
        PB_FIELD2(2, STRING, OPTIONAL, STATIC, OTHER, OpenIoT_Acknowledge, message, hardwareId, 0),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_DeviceLocation_fields[7] = {
        PB_FIELD2(1, STRING, REQUIRED, STATIC, FIRST, OpenIoT_DeviceLocation, hardwareId, hardwareId, 0),
        PB_FIELD2(2, STRING, REQUIRED, STATIC, OTHER, OpenIoT_DeviceLocation, latitude, hardwareId, 0),
        PB_FIELD2(3, STRING, REQUIRED, STATIC, OTHER, OpenIoT_DeviceLocation, longitude, latitude, 0),
        PB_FIELD2(4, STRING, OPTIONAL, STATIC, OTHER, OpenIoT_DeviceLocation, elevation, longitude, 0),
        PB_FIELD2(5, FIXED64, OPTIONAL, STATIC, OTHER, OpenIoT_DeviceLocation, eventDate, elevation, 0),
        PB_FIELD2(6, MESSAGE, REPEATED, CALLBACK, OTHER, OpenIoT_DeviceLocation, metadata, eventDate,
                  &OpenIoT_Metadata_fields),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_DeviceAlert_fields[6] = {
        PB_FIELD2(1, STRING, REQUIRED, STATIC, FIRST, OpenIoT_DeviceAlert, hardwareId, hardwareId, 0),
        PB_FIELD2(2, STRING, REQUIRED, STATIC, OTHER, OpenIoT_DeviceAlert, alertType, hardwareId, 0),
        PB_FIELD2(3, STRING, REQUIRED, STATIC, OTHER, OpenIoT_DeviceAlert, alertMessage, alertType, 0),
        PB_FIELD2(4, FIXED64, OPTIONAL, STATIC, OTHER, OpenIoT_DeviceAlert, eventDate, alertMessage, 0),
        PB_FIELD2(5, MESSAGE, REPEATED, CALLBACK, OTHER, OpenIoT_DeviceAlert, metadata, eventDate,
                  &OpenIoT_Metadata_fields),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_Measurement_fields[3] = {
        PB_FIELD2(1, STRING, REQUIRED, STATIC, FIRST, OpenIoT_Measurement, measurementId, measurementId, 0),
        PB_FIELD2(2, STRING, REQUIRED, STATIC, OTHER, OpenIoT_Measurement, measurementValue, measurementId, 0),
        PB_LAST_FIELD
};

const pb_field_t OpenIoT_DeviceMeasurements_fields[5] = {
        PB_FIELD2(1, STRING, REQUIRED, STATIC, FIRST, OpenIoT_DeviceMeasurements, hardwareId, hardwareId, 0),
        PB_FIELD2(2, MESSAGE, REPEATED, STATIC, OTHER, OpenIoT_DeviceMeasurements, measurement, hardwareId,
                  &OpenIoT_Measurement_fields),
        PB_FIELD2(3, FIXED64, OPTIONAL, STATIC, OTHER, OpenIoT_DeviceMeasurements, eventDate, measurement, 0),
        PB_FIELD2(4, MESSAGE, REPEATED, CALLBACK, OTHER, OpenIoT_DeviceMeasurements, metadata, eventDate,
                  &OpenIoT_Metadata_fields),
        PB_LAST_FIELD
};

const pb_field_t Device_fields[1] = {
        PB_LAST_FIELD
};

const pb_field_t Device_Header_fields[5] = {
        PB_FIELD2(1, ENUM, REQUIRED, STATIC, FIRST, Device_Header, command, command, 0),
        PB_FIELD2(2, STRING, OPTIONAL, STATIC, OTHER, Device_Header, originator, command, 0),
        PB_FIELD2(3, STRING, OPTIONAL, STATIC, OTHER, Device_Header, nestedPath, originator, 0),
        PB_FIELD2(4, STRING, OPTIONAL, STATIC, OTHER, Device_Header, nestedSpec, nestedPath, 0),
        PB_LAST_FIELD
};

const pb_field_t Device_RegistrationAck_fields[4] = {
        PB_FIELD2(1, ENUM, REQUIRED, STATIC, FIRST, Device_RegistrationAck, state, state, 0),
        PB_FIELD2(2, ENUM, OPTIONAL, STATIC, OTHER, Device_RegistrationAck, errorType, state, 0),
        PB_FIELD2(3, STRING, OPTIONAL, STATIC, OTHER, Device_RegistrationAck, errorMessage, errorType, 0),
        PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(OpenIoT_RegisterDevice, metadata) < 256 &&
               pb_membersize(OpenIoT_DeviceLocation, metadata) < 256 &&
               pb_membersize(OpenIoT_DeviceAlert, metadata) < 256 &&
               pb_membersize(OpenIoT_DeviceMeasurements, measurement[0]) < 256 &&
               pb_membersize(OpenIoT_DeviceMeasurements, metadata) < 256),
              YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_OpenIoT_OpenIoT_Header_OpenIoT_Metadata_OpenIoT_RegisterDevice_OpenIoT_Acknowledge_OpenIoT_DeviceLocation_OpenIoT_DeviceAlert_OpenIoT_Measurement_OpenIoT_DeviceMeasurements_Device_Device_Header_Device_RegistrationAck)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(OpenIoT_RegisterDevice, metadata) < 65536 &&
               pb_membersize(OpenIoT_DeviceLocation, metadata) < 65536 &&
               pb_membersize(OpenIoT_DeviceAlert, metadata) < 65536 &&
               pb_membersize(OpenIoT_DeviceMeasurements, measurement[0]) < 65536 &&
               pb_membersize(OpenIoT_DeviceMeasurements, metadata) < 65536),
              YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_OpenIoT_OpenIoT_Header_OpenIoT_Metadata_OpenIoT_RegisterDevice_OpenIoT_Acknowledge_OpenIoT_DeviceLocation_OpenIoT_DeviceAlert_OpenIoT_Measurement_OpenIoT_DeviceMeasurements_Device_Device_Header_Device_RegistrationAck)
#endif

