/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5-dev at Sun Nov 22 16:31:39 2015. */

#ifndef PB_RASPBERRYPI_PB_H_INCLUDED
#define PB_RASPBERRYPI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Spec_QTwHw2YxY9EFXmPrzmX4pX_Command {
    Spec_QTwHw2YxY9EFXmPrzmX4pX_Command_PING = 1,
    Spec_QTwHw2YxY9EFXmPrzmX4pX_Command_TESTEVENTS = 2,
    Spec_QTwHw2YxY9EFXmPrzmX4pX_Command_HELLOWORLD = 3
} Spec_QTwHw2YxY9EFXmPrzmX4pX_Command;

/* Struct definitions */
typedef struct _Spec_QTwHw2YxY9EFXmPrzmX4pX {
    uint8_t dummy_field;
} Spec_QTwHw2YxY9EFXmPrzmX4pX;

typedef struct _Spec_QTwHw2YxY9EFXmPrzmX4pX_ping {
    uint8_t dummy_field;
} Spec_QTwHw2YxY9EFXmPrzmX4pX_ping;

typedef struct _Spec_QTwHw2YxY9EFXmPrzmX4pX_testEvents {
    uint8_t dummy_field;
} Spec_QTwHw2YxY9EFXmPrzmX4pX_testEvents;

typedef struct _Spec_QTwHw2YxY9EFXmPrzmX4pX__Header {
    Spec_QTwHw2YxY9EFXmPrzmX4pX_Command command;
    pb_callback_t originator;
    pb_callback_t nestedPath;
    pb_callback_t nestedSpec;
} Spec_QTwHw2YxY9EFXmPrzmX4pX__Header;

typedef struct _Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld {
    pb_callback_t greeting;
    bool loud;
} Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_init_default {0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_init_default {(Spec_QTwHw2YxY9EFXmPrzmX4pX_Command)0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_ping_init_default {0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_testEvents_init_default {0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld_init_default {{{NULL}, NULL}, 0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_init_zero    {0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_init_zero {(Spec_QTwHw2YxY9EFXmPrzmX4pX_Command)0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_ping_init_zero {0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_testEvents_init_zero {0}
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld_init_zero {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_command_tag 1
#define Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_originator_tag 2
#define Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_nestedPath_tag 3
#define Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_nestedSpec_tag 4
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld_greeting_tag 1
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld_loud_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Spec_QTwHw2YxY9EFXmPrzmX4pX_fields[1];
extern const pb_field_t Spec_QTwHw2YxY9EFXmPrzmX4pX__Header_fields[5];
extern const pb_field_t Spec_QTwHw2YxY9EFXmPrzmX4pX_ping_fields[1];
extern const pb_field_t Spec_QTwHw2YxY9EFXmPrzmX4pX_testEvents_fields[1];
extern const pb_field_t Spec_QTwHw2YxY9EFXmPrzmX4pX_helloWorld_fields[3];

/* Maximum encoded size of messages (where known) */
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_size         0
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_ping_size    0
#define Spec_QTwHw2YxY9EFXmPrzmX4pX_testEvents_size 0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RASPBERRYPI_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
